# Required Render Secrets:
# - OPENROUTER_API_KEY: Your OpenRouter API key for AI processing
# - SECRET_KEY: Flask secret key for session security
#
# Optional Render Secrets:
# - MODEL: AI model to use (default: mistral-7b-instruct)
# - FLASK_DEBUG: Development mode flag (default: false)

build:
  environment: python
  pythonVersion: 3.11

services:
  - type: web
    name: chaysh-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.main:app -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_DEBUG
        value: "0"
      - key: OPENAI_API_KEY
        sync: false
      # Required environment variables - must be set in Render dashboard
      - key: OPENROUTER_API_KEY
        sync: false
        description: Your OpenRouter API key for AI processing
      - key: SECRET_KEY
        generateValue: true
        description: Flask secret key for session security
      
      # Optional environment variables
      - key: MODEL
        value: mistral-7b-instruct
        description: AI model to use for processing
      - key: OPENROUTER_API_URL
        value: https://openrouter.ai/api/v1/chat/completions
        description: OpenRouter API endpoint 