services:
  - type: web
    name: chaysh
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.main:app -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENROUTER_API_KEY
        value: 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
        sync: false 